name: Main workflow
on: [push]
jobs:

  build:
    name: Check, Build and Publish snapshot artifacts
    runs-on: ubuntu-18.04
    if: contains(github.event.head_commit.message, '[skip ci]') == false && contains(github.event.head_commit.message, '[ci skip]') == false
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/cache@v2.1.2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build and Publish the Docker image to DockerHub
        uses: docker://goreng/publish-docker-github-action:v2.4
        with:
          name: ymer/mydemo
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile
